services:
  redis:
    image: redis:alpine
    restart: always
    container_name: rssanything-redis

  rssanything:
    restart: always
    container_name: rssanything
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3012:8000'
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379